/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20abi } from "./ERC20abi";
export type { SocotraBranchManager } from "./SocotraBranchManager";
export type { SocotraFactory } from "./SocotraFactory";
export type { VoterAbi } from "./VoterAbi";
export * as factories from "./factories";
export { ERC20abi__factory } from "./factories/ERC20abi__factory";
export { SocotraBranchManager__factory } from "./factories/SocotraBranchManager__factory";
export { SocotraFactory__factory } from "./factories/SocotraFactory__factory";
export { VoterAbi__factory } from "./factories/VoterAbi__factory";
