/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20abi__factory } from "./ERC20abi__factory";
export { SocotraBranchManager__factory } from "./SocotraBranchManager__factory";
export { SocotraFactory__factory } from "./SocotraFactory__factory";
export { VoterAbi__factory } from "./VoterAbi__factory";
